import type { Metadata } from "next";
import localFont from "next/font/local";
import { Ubuntu_Condensed } from "next/font/google";
import "./globals.css";
import MiniDrawer from "@/layouts/drawer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
// Font Ubuntu Condensed dari Google Fonts
const ubuntuCondensed = Ubuntu_Condensed({
  weight: "400", // Pilih bobot sesuai kebutuhan
  subsets: ["latin"],
  variable: "--font-ubuntu-condensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${ubuntuCondensed.variable}`}>
        <MiniDrawer>
          {children}
        </MiniDrawer>
      </body>
    </html>
  );
}
